# Generated by Django 5.1.2 on 2024-10-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_bill_product_order_producttype_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
